[build]
builder = "nixpacks"
buildCommand = "npm install && cd Client && npm install && npm run build"

[deploy]
startCommand = "http-server Client/dist -p $PORT --proxy http://localhost:$PORT?"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PORT = "8000"