[build]
builder = "nixpacks"
buildCommand = "npm install && cd Client && npm install && npm run build"

[deploy]
startCommand = "npx serve -s Client/dist -l $PORT"
# Hapus baris healthcheckPath dan healthcheckTimeout

[deploy.envs]
PORT = "3000"