[build]
builder = "nixpacks"
buildCommand = "npm install && cd Client && npm install && npm run build"

[deploy]
startCommand = "serve Client/dist --listen $PORT --single"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PORT = "8000"