[build]
builder = "nixpacks"
buildCommand = "npm install && cd Client && npm install && npm run build"

[deploy]
startCommand = "serve -p $PORT Client/dist"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PORT = "8000"