[build]
builder = "nixpacks"
buildCommand = "npm install && cd Client && npm install && npm run build"

[deploy]
startCommand = "/bin/sh -c 'http-server Client/dist -p ${PORT} -a 0.0.0.0 --cors'"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PORT = "3000"