[build]
builder = "nixpacks"
buildCommand = "npm install && cd Client && npm install && npm run build"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PORT = "8000"
NIXPACKS_NODE_VERSION = "18"