[build]
builder = "nixpacks"
buildCommand = "npm install && cd Client && npm install && npm run build"

[deploy]
startCommand = "cd Client && npm run preview -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PORT = "4173"